#!/bin/sh
:<< script
# ┌────────────────────────────────────────────────────────────────────────────────┐
# │ This is Fury file which describes how to build something. It can be started by │
# │ running fury in this directory, or just executing this file from a shell.      │
# └────────────────────────────────────────────────────────────────────────────────┘

universe hell

command all         training/enums training/toplevel training/types training/opaque training/extensions
command enums       training/enums
command types       training/types
command toplevel    training/toplevel
command opaque      training/opaque
command extensions  training/extensions

project training
  module toplevel
    source src/toplevel

  module types
    source src/types

  module extensions
    source src/extensions

  module enums
    source src/enums
  
  module opaque
    source src/opaque

# ┌────────────────────────────────────────────────────────────────────────────────┐
# │ The following is the code which will be run when this file is executed. For    │
# │ more information, see: https://fury.build/                                     │
# └────────────────────────────────────────────────────────────────────────────────┘
script
    . <(echo \
        H4sIAAAAAAAAA22QSwuCQBSF9/2Kg0ToYqwcjSRqERQFPVatrMU0j5TUSh0i8MfntKvcXT \
        j3fuecO1/vpkoXr4kdgShY3dV+u+i7nPFY9l2jWDihrmFnV5EUIPfvHQu9Hp4XWYE89u3n \
        jfiZ3LNOUmFYXBcpSLn5lWatAMcxHhG6diaCUmftLjViyQQIp56DKTxvTJmiLBgOue8LFY \
        QyDEecDpQMqfRpU6qBljH+WSbhvUjyqnnHIWfnVKK6IWU65zGWJu0xtzpvxRbtHzkBAAA= \
    | base64 -id | gzip -d)
