#!/bin/bash
:<< script
# ┌────────────────────────────────────────────────────────────────────────────────┐
# │ This is Fury file which describes how to build something. It can be started by │
# │ running fury in this directory, or just executing this file from a shell.      │
# └────────────────────────────────────────────────────────────────────────────────┘

universe hell

command all         training/enums training/toplevel training/types training/opaque training/extensions
command enums       training/enums
command types       training/types
command toplevel    training/toplevel
command opaque      training/opaque
command extensions  training/extensions

project training
  module toplevel
    source src/toplevel

  module types
    source src/types

  module extensions
    source src/extensions

  module enums
    source src/enums
  
  module opaque
    source src/opaque

# ┌────────────────────────────────────────────────────────────────────────────────┐
# │ The following is the code which will be run when this file is executed. For    │
# │ more information, see: https://fury.build/                                     │
# └────────────────────────────────────────────────────────────────────────────────┘
script
    BIN=fury;([ -f "$HOME/.cache/.fury" ] || (mkdir -p "$HOME/.cache" && wget -qO "$HOME/.cache/.fury" get.fury.build 2> /dev/null || curl -sL get.fury.build > "$HOME/.cache/.fury")) && [ "$(md5sum "$HOME/.cache/.fury" 2> /dev/null | head -c32 || md5 -q "$HOME/.cache/.fury" | head -c32)" = 35667dbf696a1c37ab52d50d1f753d2b ] && sh "$HOME/.cache/.fury" "$@"
