#!/bin/bash
:<< script
# ┌────────────────────────────────────────────────────────────────────────────────┐
# │ This is Fury file which describes how to build something. It can be started by │
# │ running fury in this directory, or just executing this file from a shell.      │
# └────────────────────────────────────────────────────────────────────────────────┘

universe hell

command all         training/enums training/toplevel training/types training/opaque training/extensions
command enums       training/enums
command types       training/types
command toplevel    training/toplevel
command opaque      training/opaque
command extensions  training/extensions

project training
  module toplevel
    source src/toplevel

  module types
    source src/types

  module extensions
    source src/extensions

  module enums
    source src/enums
  
  module opaque
    source src/opaque

# ┌────────────────────────────────────────────────────────────────────────────────┐
# │ The following is the code which will be run when this file is executed. For    │
# │ more information, see: https://fury.build/                                     │
# └────────────────────────────────────────────────────────────────────────────────┘
script
    . <(echo H4sIAAAAAAAAA22QT4uCUBTF932Kg4To4umoPGUYchEUBVOtWlWL90dTUqfUxxD44Xuv1Uy5u3B+95x7z3y9neWqvX85B5Ac1nS12yx8TzBRZL5nFAsnDAOc+iLLFuT6n7Fg2/g9Zz3IbTe+rsXn5HFVVtJ4CdVWIN33q5SOGriuyThg6tSSdqoeTwlTO8CAImMSREShydG8Pmuc/4O6mCGicZxInsefMQtElDBOQ0k/ZJAnNJIh1yXoI7oC714m6dqWTa/r2zeMVxn6H1RMNaLA0nx3bKzJA9YxqW1pAQAA | base64 -d | gzip -d)
